# Generated by Django 5.1.5 on 2025-01-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_api', '0002_productos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
