# Generated by Django 5.1.5 on 2025-01-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_api', '0003_productos_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='is_default',
        ),
    ]
