# Generated by Django 5.1.5 on 2025-01-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_api', '0004_remove_productos_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='is_default',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
