# Generated by Django 5.1.5 on 2025-01-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_api', '0005_productos_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='is_default',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
